name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  get-repo-info:
    needs: pre-commit
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  build-and-test:
    needs: get-repo-info
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    uses: divkix/reusable-workflows/.github/workflows/build-and-test-python-package.yml@main
    with:
      custom_commands: pytest tests.py -v
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}

  build-docker:
    needs: build-and-test
    used: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      tag: ${{ needs.get-repo-info.outputs.tag }}
      push: false
      update_description: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  automerge-dependabot-pr:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs:
      - build-and-test
      - build-docker
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
