name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  docker-build:
    name: Build Image
    needs: create-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set ENV Variables
        id: vars
        run: |
          IMG="$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"
          TAG="$(git tag | sort -V | tail -1)"
          echo "BUILD_VER=${TAG}" >> $GITHUB_ENV
          echo "::set-output name=tag::${TAG}"
          echo "IMAGE=${IMG}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.IMAGE }}:latest
            ghcr.io/${{ env.IMAGE }}:${{ env.BUILD_VER }}
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.BUILD_VER }}
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
            org.opencontainers.image.ref.name=${{ env.GIT_REF }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.BUILD_VER }}

    outputs:
      BUILD_VER: ${{ steps.vars.outputs.tag }}

  automerge-dependabot-pr:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs:
      - pre-commit
      - build-and-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3.0
        with:
          target: minor
