name: Close PR for requirements.txt

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
    branches:
      - main
    paths:
     - requirements.txt

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/close-pull@v2
      with:
        comment: Auto-closing PR as requirements.txt does not need dependabot updates.
        delete-branch: true
