name: Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # fetch some info from repo such as latest tag and name in lowercase
  get-repo-info:
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  # build the docker image and push it to docker hub and ghcr
  docker-build:
    needs: get-repo-info
    used: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      tag: ${{ needs.get-repo-info.outputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
