name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  # only run this step when the tag is not already created
  update-version:
    needs: pre-commit
    uses: divkix/reusable-workflows/.github/workflows/update-python-package-version.yml@main
    with:
      version_level: ${{ github.event.inputs.version_level }}

  # fetch some info from repo such as latest tag and name in lowercase
  get-repo-info:
    if: always()
    needs: update-version
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  # build the docker image and push it to docker hub and ghcr
  docker-build:
    if: always()
    needs: get-repo-info
    used: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      tag: ${{ needs.get-repo-info.outputs.tag }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # create a release on github
  create-release:
    if: always()
    needs:
      - docker-build
      - get-repo-info
    uses: divkix/reusable-workflows/.github/workflows/create-release.yml@main
    with:
      tag: ${{ needs.get-repo-info.outputs.tag }}
      body: |-
        ${{ github.event.repository.name }} ${{ needs.get-repo-info.outputs.tag }}

        Docker Images:
        `ghcr.io/${{ github.repository_owner }}/${{ needs.get-repo-info.outputs.repo_name }}:${{ needs.get-repo-info.outputs.tag }}`
        `docker.io/${{ github.repository_owner }}/${{ needs.get-repo-info.outputs.repo_name }}:${{ needs.get-repo-info.outputs.tag }}`
